<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:math="http://www.w3.org/2005/xpath-functions/math"
    exclude-result-prefixes="xs math"
    version="3.0">
    
    <xsl:variable name="curatorial_mapping" as="map(xs:string, xs:string)" select="
        (: update the gen mappings? :)
        map {
        'gen': 'General Collection, Beinecke Rare Book and Manuscript Library, Yale University.'
        , 'genm': 'General Collection, Beinecke Rare Book and Manuscript Library, Yale University.'
        , 'genam': 'General Collection, Beinecke Rare Book and Manuscript Library, Yale University.'
        , 'genem': 'General Collection, Beinecke Rare Book and Manuscript Library, Yale University.'
        , 'jwj': 'James Weldon Johnson Memorial Collection in the Yale Collection of American Literature, Beinecke Rare Book and Manuscript Library.'
        , 'osb': 'James Marshall and Marie-Louise Osborn Collection, Beinecke Rare Book and Manuscript Library, Yale University.'
        , 'wa': 'Yale Collection of Western Americana Beinecke Rare Book and Manuscript Library.'
        , 'ycal': 'Yale Collection of American Literature, Beinecke Rare Book and Manuscript Library.'
        , 'ycgl': 'Yale Collection of German Literature, Beinecke Rare Book and Manuscript Library.'
        }  "/> 
    
    <xsl:variable name="accession_type_mapping" as="map(xs:string, xs:string)" select="
        map {
        'gift': 'Gift of'
        , 'purchase': 'Purchased from'
        , 'deposit': 'Deposit from'
        , 'transer': 'Transfer from'
        }" />
    
    <!-- update this as needed, since not all codes have proper translations -->
    <xsl:variable name="fund_mapping" as="map(xs:string, xs:string)" select="
        map {
        'A-CCOM': 'A-CCOM'
        , 'ACQMK': 'Acquisition Meserve-Kundhart Fund'
        , 'AFRDON': 'Gaylord Donnelley Fund'
        , 'AFRGEN': 'African General Fund'
        , 'AFRINV': 'African General Fund'
        , 'AFRSER': 'African General Fund'
        , 'AFRSPL': 'African Special Use Fund'
        , 'ALTSCH': 'Frank Altschul Fund'
        , 'ALVORD': 'George B. Alvord Fund'
        , 'AMERLT': 'American Literature Fund'
        , 'ANDRSN': 'Edith French Anderson memorial Fund'
        , 'Anonymous': 'Anonymous Fund'
        , 'ARTJFFE': 'Mr. and Mrs. William B. Jaffe Fund'
        , 'ARTCON': 'G.A. funds'
        , 'ARTMON': 'G.A. fund for Art Library monographs'
        , 'Babb': 'James Tinkham Babb, ''24, Fund'
        , 'BAKER': 'Alfred Z. Baker, Jr. Fund'
        , 'BARNDA': 'Danford N. Barney, Jr. Fund'
        , 'BARNDN': 'D. Newton Barney Fund'
        , 'BEIEND': 'E. J. and F. W. Beinecke Rare Book Endowment Fund'
        , 'BEIEXP': 'Beinecke Expendable Fund'
        , 'BEIGER': 'Beinecke German Literature Collection Fund'
        , 'BEILEG': 'Edwin J. Beinecke Book Fund'
        , 'BEIMAI': 'Beinecke Rare Book &amp; Manuscript Library Maintenance Fund'
        , 'BEIN1': 'Beinecke No. 1 Fund'
        , 'BEINEC': 'Edwin J. Beinecke, ''07, Frederick W. Beinecke, ''09S, and Walter Beinecke, ''10 Fund'
        , 'BEINFW': 'Frederick W. Beinecke Fund'
        , 'BEIRES': 'Beinecke Rare Book &amp; Capital Reserve Fund'
        , 'BEISER': 'Edwin J. Beinecke ''07, Frederick W. Beinecke, ''09S, and Walter Beinecke, ''10 Fund'
        , 'BEISRL': 'Edwin J. Beinecke, ''07, Frederick W. Beinecke, ''09S, and Walter Beinecke, ''10 Fund'
        , 'BEQBAL': 'Edwin J. Beinecke #2'
        , 'BEINWA': 'Frederick W. and Carrie S. Beinecke Fund for Western Americana'
        , 'BENET': 'Plate: Benet Endowment Fund'
        , 'BERNHM': 'Elinor and Leonard Bernheim Fund'
        , 'BFIELD': 'Bernice Field Fund'
        , 'BKPOOL': 'G. A. funds'
        , 'BLOCK': 'Ruth &amp; Alec Block Fund'
        , 'BOLLIN': 'Bollingen Fund'
        , 'BROCH': 'H. F. Broch de Rothermann Memorial Fund'
        , 'BROOKR': 'T. Kimball Brooker Italian Renaissance Fund'
        , 'BULKLY': 'Jonathan O. Bulkley Fund'
        , 'CALLA': 'Jack Callaway Fund'
        , 'CARBEI': 'Carrie S. Beinecke Fund'
        , 'CARY': 'Mary Flagler Cary Fund'
        , 'CASE': 'Charles Blackwell Case Fund'
        , 'CERUTTI': 'CERUTTI'
        , 'CHILDA': 'Albert H. Childs Fund'
        , 'CHILDS': 'Starling W. Childs Library Fund'
        , 'CLAPP': 'Frederick M. Clapp Fund'
        , 'CLASS': 'Class of 1872 Fund'
        , 'CL1884': 'Class of 1884, Yale College, Fund'
        , 'CNEFEL': 'Hadumoth Cnefelius Fund'
        , 'COE-1': 'William Robertson Coe Fund No. 1 [Western Americana]'
        , 'COE-2': 'William Robertson Coe American Studies Fund'
        , 'COE-3': 'William Robertson Coe Fund No. 3 [Western Americana]'
        , 'Cole': 'George Watson Cole Bibliographical Collection Fund'
        , 'CORWIT': 'John W. Corwith Memorial Fund'
        , 'Cowles': 'William Hutchinson Cowles Memorial Book Fund'
        , 'DAGGET': 'Naphtali Daggett Fund'
        , 'DAVENPO': 'John Davenport Fund (Music)'
        , 'DESILV': 'From the fund in memory of Albert DeSilver Yale 1910'
        , 'DEVDIS': 'Collection Development Discretionary Fund'
        , 'DEXTER': 'Fund in memory of Franklin Bowditch Dexter, Secretary, Librarian, Historian of Yale'
        , 'DIVLATU': 'Latourette Fund (Divinity)'
        , 'DOOLIT': 'Hilda Doolittle Fund'
        , 'DPBHBSA': 'G.A. funds'
        , 'DPBNASC': 'G.A. funds'
        , 'DPBNCAS': 'G.A. funds'
        , 'DPBNHAR': 'G.A. funds'
        , 'DRAPER': ' William H. Draper II Fund'
        , 'Driggs': 'Henry P. Driggs Memorial Fund'
        , 'DUPONT': 'Henry B. DuPont Fund'
        , 'DURAND': 'John Ewing Durand Memorial Fund'
        , 'DWIGHT': 'Elizabeth Wakeman Dwight Memorial Fund'
        , 'EBERST': 'Edward E. Eberstadt Fund'
        , 'EGLES': 'William C. Egleston Fund'
        , 'ELIOTE': 'Eliot Ellsworth Fund (SML/BRBL)'
        , 'ENGEL': 'Henny and Rudolf Engelbarts Fund'
        , 'EXCHAN': 'Exchange Fund'
        , 'FARNAM': 'Ann S. Farnam Fund'
        , 'FELHMR': 'Jeanette Fellheimer Fund'
        , 'FIELD': 'Theron Field Fund'
        , 'FLETCH': 'Henry Fletcher Fund'
        , 'FRANK': 'Hyman Frank Book Fund for the Judaica Collection'
        , 'FRENCH': 'Edith and Richard French Fund'
        , 'FROST': 'Frost American Literature Fund'
        , 'GABRIE': 'George Gabriel Fund'
        , 'GALLUP': 'Donald C. Gallup Fund'
        , 'GARVER': 'Milton Garver Fund'
        , 'GAYLES': 'Gay and lesbian material fund'
        , 'GOODH': 'Howard L. Goodhart Memorial Fund'
        , 'GENAPP': 'Law Library General Appropriations '
        , 'GIAMAT': 'A. Bartlett Giamatti Fund No.2'
        , 'GERL&amp;L': 'GERL&amp;L - G.A. funds'
        , 'GLEASN': 'GLEASN'
        , 'GOLDST': 'Herman H. Goldstein, M.D. (''23S, ''27M) Fund'
        , 'GRANT': 'GRANT'
        , 'GREBLT': 'Martin Greenblatt Foundation Book Fund in American Literature'
        , 'H.D.': 'Hilda Doolittle Fund'
        , 'HADLEY': 'Helen Morris Hadley Fund'
        , 'HANNA': 'Archibald Hanna Fund'
        , 'HARIBN': 'Cecil J. Harribine Fund'
        , 'HARPER': 'Lathrop Colgate Harper Fund'
        , 'HEALEY': 'Horace Grant Healey Shorthand Collection Fund'
        , 'Healy': 'William Arnold Healy Fund'
        , 'HILLES': 'Frederick W. Hilles Fund'
        , 'HISTRY': 'G.A. funds'
        , 'HODGDN': 'Ernest F. Hodgdon Fund'
        , 'HOMES': 'Henry Homes Fund'
        , 'HOSKIN': 'Arthur Corbitt Hoskins Memorial Fund'
        , 'HUNT': 'Rachel McMasters Miller Hunt Fund'
        , 'INSERT': 'INSERT'
        , 'IPLSML': 'IPLSML'
        , 'JENNIN': 'Walter Jennings Memorial Fund'
        , 'JACKSOJ': 'John Herrick Jackson Fund'
        , 'JUDBALL': 'Andrew D. Ball'
        , 'JUDFRAN': 'Henrietta and Hyman Frank Fund'
        , 'JUDFISH': 'Esther A. Fishman Memorial Fund'
        , 'JUDJUD': 'The Samuel B. Rose Judaica Fund'
        , 'JUDKOHU': 'Alexander Kohut Memorial Collection'
        , 'JUDKUM': 'Oscar Charles Kumble'
        , 'JUDLITT': 'Judaica Book Fund of the Lucius N. Littauer Foundation'
        , 'JUDLOWE': 'Alexander Lowenthal Judaica Book Fund'
        , 'JUDMEND': 'William &amp; Stella Mendelsohn Fund'
        , 'JUDMON': 'G.A. funds'
        , 'JUDNEUS': 'Walter Neustadt, Jr. Book Fund'
        , 'JUDNEWM': 'Rosalyn and Joseph Newman Fund for Yiddish Literature'
        , 'JUDRIES': 'Joseph and Saddie Riesman Fund'
        , 'JUDROLA': 'The Roland Book Fund in Judaic Studies'
        , 'JUDSIEG': 'Henry Jonathan Siegel Fund'
        , 'JWJ': 'James Weldon Johnson Memorial Collection of Negro Arts &amp; Letters Fund'
        , 'KENNED': 'Stanton Francis Kennedy Fund'
        , 'Kingsley Trust': 'Kingsley Trust - Kingsley Trust Association Fund'
        , 'KITMIL': 'Kittymiller'
        , 'KOHUT': 'Alexander Kohut Memorial Collection'
        , 'KRAUS': 'H.P. Kraus Fund'
        , 'KROM': 'Arthur D. Krom Fund'
        , 'KROMBLK': 'Arthur D. Krom Fund'
        , 'KROMCON': 'Arthur D. Krom Fund'
        , 'KROMMON': 'Arthur D. Krom Fund'
        , 'KUMBLE': 'Oscar Charles Kumble Fund'
        , 'LACHOWE': 'Jane and Walter Howe ''29 Fund for Material Relating to Latin America'
        , 'LADAMO': 'Laura K. and Valerian Lada-Mocarski Fund'
        , 'Larned': 'Irene Battell Larned Fund'
        , 'LATGEN': 'G.A. funds'
        , 'LAZARE': 'Ramona Lazare Fund'
        , 'LECKROM': 'G. A. American and Commonwealth monographs'
        , 'LECSER': 'American and Commonwealth serials'
        , 'LIBASC': 'Library Associates Fund'
        , 'LIBEND': 'Library Associates Endowment Fund'
        , 'LIBERT': 'Herman W. Liebert Book Fund'
        , 'LINSLY': 'Noah and Jared Linsly Fund'
        , 'MACKIN': 'MacKinnon Family Fund'
        , 'MALBIN': 'Lydia Winston Malbin Archives Fund (UAG)'
        , 'MANWAR': 'Elizabeth W. Manwaring Fund'
        , 'MAPCOL': 'Map Collection Fund'
        , 'MAPEND': 'Map Endowment Fund'
        , 'MAPGEN': 'G.A. funds'
        , 'MAPHOLT': 'Howard M. Holtzmann Fund'
        , 'MATTHI': 'Francis O. Matthiesen Fund'
        , 'MAYPW': 'Peyton W. May Fund'
        , 'MCCLIN': 'Walter McClintock Memorial Fund'
        , 'MCCULL': 'Hall Park McCullough Fund'
        , 'MCGUIR': 'Hubert Amer McGuire Memorial Fund'
        , 'MCKIM': 'William L. McKim Fund'
        , 'MEMORA': 'Memorabilia Fund'
        , 'MENDSN': 'William &amp; Stella Mendelsohn Fund'
        , 'MENNER': 'Robert James Menner Fund'
        , 'MERCER': 'MERCER [One-time-only purchase]'
        , 'MILLER': 'Winlock William Miller, Jr. Memorial Fund'
        , 'MISCEL': 'Miscellaneous Funds'
        , 'MISGFT': 'Miscellaneous gift fund'
        , 'MISJUD': 'Judaica gifts fund'
        , 'MOFFAT': 'Douglas M. Moffat Fund'
        , 'MORSE': 'Susan A.E. Morse and William Inglis Morse Fund for the Purchase of Canadiana'
        , 'MURPHY': 'Lawrence S. Murphy Fund, Yale 1939'
        , 'NATHAN': 'Adele Gutman Nathan Theatrical Collection Fund'
        , 'NETLON': 'George Henry Nettleton Fund'
        , 'NEUFEL': 'Philip and Margaret Neufeld Fund of the Yale Library Associates'
        , 'NEUSDT': 'Walter Neustadt, Jr. Book Fund'
        , 'ONEILC': 'Eugene G. O''Neill Memorial Fund'
        , 'ONEILE': 'Eugene G. O''Neill Memorial Fund'
        , 'OSBGFT': 'Osborn Gift Fund'
        , 'OSBHAZ': 'Hazel M. Osborn Fund'
        , 'OSBORN': 'James Marshall and Marie-Louise Osborn Collection Fund'
        , 'PENNIN': 'Penniman Memorial Library Fund'
        , 'PENWAR': 'PENWAR [One-time-only for purchase of Robert Penn Warren archive]'
        , 'PERRY': 'Beinecke Foundation'
        , 'PERRY2': 'Widgeon Point Charitable Foundation'
        , 'PHELPS': 'William Lyon Phelps Memorial Fund'
        , 'PFORZH': 'Walter L. Pforzheimer Fund'
        , 'PLAIN': 'Plain fund'
        , 'PL480': 'PL480'
        , 'POUND': 'Ezra Pound Archive Fund'
        , 'POUNGF': 'Pound Studies Center Gift Fund'
        , 'PURCHCD': 'Purchase Card'
        , 'QUILLV': 'Violet Quill Fund'
        , 'RABINO': 'Louis Mayer Rabinowitz Memorial Fund'
        , 'RBSPEC': 'RBSPEC [One-time-only purchase]'
        , 'REPLACE': 'Replacements'
        , 'REESE': 'Library Associates Fund'
        , 'REYNOLM': 'Maude and Horatio Reynolds Fund'
        , 'ROLAND': 'Roland Judaica Collection'
        , 'ROMCLAP': 'Frederick M. Clapp Fund'
        , 'ROMCON': 'G.A. funds for romance continuations'
        , 'ROML&amp;L': 'ROML&amp;L - G.A. funds'
        , 'ROMPOOL': 'G.A. funds'
        , 'ROMSER': 'G.A. funds for romance serials'
        , 'ROSENA': 'Arthur M. Rosenbloom Fund'
        , 'ROSENC': 'Charles J. Rosenbloom Fund'
        , 'SARP': 'South African Research Program Fund'
        , 'SCHEUR': 'SCHEUR'
        , 'SCHWAL': 'Jacob &amp; Ruth Schwalbe Memorial Fund'
        , 'SHIRLY': 'Jockey Hollow Fund'
        , 'SHORTR': 'SHORTR'
        , 'SLABK': 'Slavic Fund'
        , 'SLACHO': 'Chopivsky Family Book Fund'
        , 'SLACON': 'G. A. funds for Slavic continuations'
        , 'SLAGEN': 'G. A. general Slavic funds'
        , 'SLAGIFT': 'Slavic Collection miscellaneous gift fund'
        , 'SLAOUSP': 'P.D. Oupensky Memorial Collection'
        , 'SLAEXC': 'Slavic Exchange'
        , 'SLAVIC': 'Slavic General Fund'
        , 'SLEWIS': 'Sinclair Lewis Fund'
        , 'SLVGEN': 'Slavic General Fund'
        , 'SLVINV': 'SLVINV'
        , 'SMALL': 'Robert W. Small Fund'
        , 'SMITH': 'Chandler White and Philena Pennell Smith Acquisitions Fund'
        , 'SMITHP': 'Purchased from the income of the Paul L. Smith, ''41 Book Fund'
        , 'SOCSCI': 'G. A. Social Science Fund'
        , 'SOMMER': 'Gift of Frank H. Sommer, Class of 1944'
        , 'SOUTHW': 'Edward Wells Southworth Fund'
        , 'SPECK': 'William A. Speck Fund'
        , 'SPCIAL': 'Special purchase account'
        , 'SRLBEI': 'Edwin J. Beinecke, ''07, Frederick W. Beinecke, ''09, and Walter Beinecke, ''10 Fund'
        , 'SRLPLA': 'SRLPLA'
        , 'STEPHA': 'Ruth Stephan Fund'
        , 'STREET': 'Thomas W. Streeter Fund'
        , 'STRVAR': 'Thomas W. Streeter Texas Collection'
        , 'SWAN': 'The Bradford F. and Lila L. Swan Fund'
        , 'TAYLHC': 'Henry C. Taylor Fund'
        , 'TAYLR': 'Robert H. Taylor Fund'
        , 'TAYLW': 'William A. Taylor Memorial Fund'
        , 'THEATR': 'Theatre Guild Fund'
        , 'TINKER': 'Chauncey Brewster Tinker Prize Fund'
        , 'TORENC': 'Helen Hersh Torrence Fund'
        , 'TUTTLE': 'Donald S. Tuttle Book Fund'
        , 'VANVEC': 'Carl Van Vechten Fund'
        , 'VANSIN': 'Adrian Van Sinderen, ''10 Fund'
        , 'VIETOR': 'Alexander O. Vietor Fund'
        , 'WAGNER': 'Henry R. Wagner Fund'
        , 'WAGSTA': 'David Wagstaff Memorial Fund'
        , 'WAITH': 'Margaret Deakers and Eugene Mersereau Waith Fund'
        , 'WHITNY': 'James Lyman Whitney Fund'
        , 'WILDER': 'Thornton Wilder Memorial Fund'
        , 'WINDHM': 'Donald Windham-Sandy Campbell Collection Endowment Fund'
        , 'WING': 'Donald G. Wing Fund'
        , 'WGCP': 'Working Group in Contemporary Poetry Fund'
        , 'WOOLSEY': 'Woolsey Library Fund in Public Law and Diplomatic History'
        , 'WRIGHT': 'James Howell Wright Fund'
        , 'XCHANG': 'Exchange Fund'
        , 'Yale Memorabilia': 'Yale Memorabilia - Yale Memorabilia Fund'
        }
        "/>
    
</xsl:stylesheet>
